version: '3'
services:
  db:
    build: ./postgres
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    user: root
  web:
    build: ./python
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./src:/myapp
    depends_on:
      - db
  pgadmin4:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin4
    ports:
      - 8080:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    restart: always

